apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
  labels:
    app: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: 074047115132.dkr.ecr.us-east-1.amazonaws.com/server:b07b7257bfbc580f6ffd2884365dd0ee6b92af06
        imagePullPolicy: Always
        volumeMounts:
          - name: grpc-server-secrets
            mountPath: "/mnt/secrets-store"
            readOnly: true
        ports:
        - containerPort: 8085
        env:
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: pghost
                key: PG_HOST
          - name: PG_PORT
            valueFrom:
              secretKeyRef:
                name: pgport
                key: PG_PORT
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: pguser
                key: PG_USER
          - name: PG_PASS
            valueFrom:
              secretKeyRef:
                name: pgpass
                key: PG_PASS
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: pgdb
                key: PG_DB
      volumes:
        - name: grpc-server-secrets
          csi:
            driver: secrets-store.csi.x-k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: grpc-server-secrets
