apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
   name: grpc-server-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:074047115132:secret:grpc-secrets-JmATyd"
          jmesPath: 
              - path: PG_HOST
                objectAlias: PG_HOST
              - path: PG_PORT
                objectAlias: PG_PORT
              - path: PG_USER
                objectAlias: PG_USER
              - path: PG_PASS
                objectAlias: PG_PASS
              - path: PG_DB
                objectAlias: PG_DB